{
    "name": "Servigas Core",
    "summary": "Tema Liquid Glass v2, hubs Inventario/Ventas/Compras/Facturación",
    "description": """
Módulo base de Servigas: assets SCSS (marca llama, tipografía Montserrat),
personalización POS y backend Odoo 19, hubs KPI cards de ingreso por sección.
    """,
    "author": "Servigas",
    "website": "https://github.com/mauriciosoyastor/servigas",
    "category": "Servigas",
    "version": "19.0.1.20.33",
    "license": "LGPL-3",
    "depends": [
        "base",
        "base_setup",
        "web",
        "mail",
        "product",
        "point_of_sale",
        "pos_discount",
        "stock",
        "sale_management",
        "purchase",
        "account",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/sg_price_list_import_views.xml",
        "data/hub_inventory_data.xml",
        "data/hub_sales_data.xml",
        "data/hub_purchase_data.xml",
        "data/hub_accounting_data.xml",
        "data/launcher_tiles_data.xml",
        "data/hide_native_apps.xml",
        "views/servigas_app_menu.xml",
        "views/hub_menus.xml",
        "views/launcher_menus.xml",
        "views/login_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            (
                "before",
                "web/static/src/scss/base_frontend.scss",
                "servigas_core/static/src/scss/servigas_tokens.scss",
            ),
            "servigas_core/static/src/scss/servigas_login.scss",
        ],
        "web.assets_backend": [
            (
                "before",
                "web/static/src/scss/bootstrap_overridden.scss",
                "servigas_core/static/src/scss/servigas_tokens.scss",
            ),
            "servigas_core/static/src/scss/servigas_backend.scss",
            "servigas_core/static/src/scss/servigas_rail.scss",
            "servigas_core/static/src/scss/servigas_list.scss",
            "servigas_core/static/src/scss/servigas_launcher.scss",
            "servigas_core/static/src/scss/servigas_hub.scss",
            "servigas_core/static/src/scss/servigas_onboarding_smoke.scss",
            "servigas_core/static/src/js/services/sg_title_service.js",
            "servigas_core/static/src/js/services/sg_hub_service.js",
            "servigas_core/static/src/js/services/sg_pos_entry.js",
            "servigas_core/static/src/js/services/sg_pos_theme.js",
            "servigas_core/static/src/js/services/sg_onboarding_full_catalog.js",
            "servigas_core/static/src/js/services/sg_onboarding_tour.js",
            "servigas_core/static/src/js/services/sg_onboarding_chrome.js",
            "servigas_core/static/src/js/services/sg_onboarding_persist.js",
            "servigas_core/static/src/js/services/sg_onboarding_host.js",
            "servigas_core/static/src/js/services/sg_onboarding_smoke.js",
            "servigas_core/static/src/js/services/sg_shell_path.js",
            "servigas_core/static/src/js/services/sg_onboarding_smoke_boot.js",
            "servigas_core/static/src/js/services/sg_onboarding_smoke_service.js",
            "servigas_core/static/src/js/services/sg_onboarding_host_boot.js",
            "servigas_core/static/src/js/services/sg_onboarding_host_service.js",
            "servigas_core/static/src/js/services/sg_launcher_service.js",
            "servigas_core/static/src/js/chrome/sg_rail_context.js",
            "servigas_core/static/src/js/services/sg_rail_service.js",
            "servigas_core/static/src/js/services/sg_nav_user_service.js",
            "servigas_core/static/src/js/launcher/sg_launcher_tile.xml",
            "servigas_core/static/src/js/launcher/sg_launcher_tile.js",
            "servigas_core/static/src/js/launcher/sg_launcher_shell.xml",
            "servigas_core/static/src/js/launcher/sg_launcher_shell.js",
            "servigas_core/static/src/js/hubs/sg_hub_section_body.xml",
            "servigas_core/static/src/js/hubs/sg_hub_section_body.js",
            "servigas_core/static/src/js/hubs/sg_app_hub.xml",
            "servigas_core/static/src/js/hubs/sg_app_hub.js",
            "servigas_core/static/src/js/hubs/inventory_hub.js",
            "servigas_core/static/src/js/hubs/sales_hub.js",
            "servigas_core/static/src/js/hubs/purchase_hub.js",
            "servigas_core/static/src/js/hubs/accounting_hub.js",
            "servigas_core/static/src/js/launcher/app_launcher.xml",
            "servigas_core/static/src/js/launcher/app_launcher.js",
            "servigas_core/static/src/js/chrome/sg_rail_nav.xml",
            "servigas_core/static/src/js/chrome/sg_rail_nav.js",
            "servigas_core/static/src/js/chrome/sg_mobile_bottom_bar.xml",
            "servigas_core/static/src/js/chrome/sg_mobile_bottom_bar.js",
            "servigas_core/static/src/js/chrome/sg_webclient_patch.xml",
            "servigas_core/static/src/js/chrome/sg_webclient_patch.js",
        ],
        "point_of_sale._assets_pos": [
            "servigas_core/static/src/scss/servigas_tokens.scss",
            "servigas_core/static/src/scss/servigas_pos.scss",
            "servigas_core/static/src/scss/servigas_onboarding_smoke.scss",
            "servigas_core/static/src/js/services/sg_pos_theme.js",
            "servigas_core/static/src/js/services/sg_pos_order_discount.js",
            "servigas_core/static/src/js/pos/sg_product_screen_order_discount.js",
            "servigas_core/static/src/js/services/sg_onboarding_tour.js",
            "servigas_core/static/src/js/services/sg_onboarding_chrome.js",
            "servigas_core/static/src/js/services/sg_onboarding_smoke.js",
            "servigas_core/static/src/js/services/sg_shell_path.js",
            "servigas_core/static/src/js/services/sg_onboarding_smoke_boot.js",
            "servigas_core/static/src/js/services/sg_onboarding_smoke_pos.js",
        ],
        "web._assets_primary_variables": [
            (
                "after",
                "web/static/src/webclient/navbar/navbar.variables.scss",
                "servigas_core/static/src/scss/servigas_primary_variables.scss",
            ),
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
